src/Entity/Kamer.php
<?php

namespace App\Entity;

use App\Repository\KamerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=KamerRepository::class)
 */
class Kamer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Soort::class, inversedBy="kamers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $soortid;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prijs;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="kamerid")
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity=Reservering::class, mappedBy="kamerid")
     */
    private $reserverings;

    /**
     * @ORM\Column(type="integer")
     */
    private $kamer_nr;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->reserverings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSoortid(): ?Soort
    {
        return $this->soortid;
    }

    public function setSoortid(?Soort $soortid): self
    {
        $this->soortid = $soortid;

        return $this;
    }

    public function getPrijs(): ?float
    {
        return $this->prijs;
    }

    public function setPrijs(?float $prijs): self
    {
        $this->prijs = $prijs;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setKamerid($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getKamerid() === $this) {
                $image->setKamerid(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Reservering[]
     */
    public function getReserverings(): Collection
    {
        return $this->reserverings;
    }

    public function addReservering(Reservering $reservering): self
    {
        if (!$this->reserverings->contains($reservering)) {
            $this->reserverings[] = $reservering;
            $reservering->setKamerid($this);
        }

        return $this;
    }

    public function removeReservering(Reservering $reservering): self
    {
        if ($this->reserverings->contains($reservering)) {
            $this->reserverings->removeElement($reservering);
            // set the owning side to null (unless already changed)
            if ($reservering->getKamerid() === $this) {
                $reservering->setKamerid(null);
            }
        }

        return $this;
    }

    public function getKamerNr(): ?int
    {
        return $this->kamer_nr;
    }

    public function setKamerNr(int $kamer_nr): self
    {
        $this->kamer_nr = $kamer_nr;

        return $this;
    }
}

src/Form/KamerType.php
<?php

namespace App\Form;

use App\Entity\Kamer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class KamerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('prijs')
            ->add('soortid')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Kamer::class,
        ]);
    }
}

src/Controller/KamerController.php
<?php

namespace App\Controller;

use App\Entity\Kamer;
use App\Form\KamerType;
use App\Repository\KamerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/kamer")
 */
class KamerController extends AbstractController
{
    /**
     * @Route("/", name="kamer_index", methods={"GET"})
     */
    public function index(KamerRepository $kamerRepository): Response
    {
        return $this->render('kamer/index.html.twig', [
            'kamers' => $kamerRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="kamer_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $kamer = new Kamer();
        $form = $this->createForm(KamerType::class, $kamer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($kamer);
            $entityManager->flush();

            return $this->redirectToRoute('kamer_index');
        }

        return $this->render('kamer/new.html.twig', [
            'kamer' => $kamer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="kamer_show", methods={"GET"})
     */
    public function show(Kamer $kamer): Response
    {
        return $this->render('kamer/show.html.twig', [
            'kamer' => $kamer,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="kamer_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Kamer $kamer): Response
    {
        $form = $this->createForm(KamerType::class, $kamer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('kamer_index');
        }

        return $this->render('kamer/edit.html.twig', [
            'kamer' => $kamer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="kamer_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Kamer $kamer): Response
    {
        if ($this->isCsrfTokenValid('delete'.$kamer->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($kamer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('kamer_index');
    }
}

templates/kamer/_delete_form.html.twig
<form method="post" action="{{ path('kamer_delete', {'id': kamer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ kamer.id) }}">
    <button class="btn">Delete</button>
</form>

templates/kamer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Kamer{% endblock %}

{% block body %}
    <h1>Edit Kamer</h1>

    {{ include('kamer/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('kamer_index') }}">back to list</a>

    {{ include('kamer/_delete_form.html.twig') }}
{% endblock %}

templates/kamer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Kamer index{% endblock %}

{% block body %}
    <h1>Kamer index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prijs</th>
                <th>Kamer_nr</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for kamer in kamers %}
            <tr>
                <td>{{ kamer.id }}</td>
                <td>{{ kamer.prijs }}</td>
                <td>{{ kamer.kamerNr }}</td>
                <td>
                    <a href="{{ path('kamer_show', {'id': kamer.id}) }}">show</a>
                    <a href="{{ path('kamer_edit', {'id': kamer.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('kamer_new') }}">Create new</a>
{% endblock %}

templates/kamer/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Kamer{% endblock %}

{% block body %}
    <h1>Create new Kamer</h1>

    {{ include('kamer/_form.html.twig') }}

    <a href="{{ path('kamer_index') }}">back to list</a>
{% endblock %}

templates/kamer/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Kamer{% endblock %}

{% block body %}
    <h1>Kamer</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ kamer.id }}</td>
            </tr>
            <tr>
                <th>Prijs</th>
                <td>{{ kamer.prijs }}</td>
            </tr>
            <tr>
                <th>Kamer_nr</th>
                <td>{{ kamer.kamerNr }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('kamer_index') }}">back to list</a>

    <a href="{{ path('kamer_edit', {'id': kamer.id}) }}">edit</a>

    {{ include('kamer/_delete_form.html.twig') }}
{% endblock %}